name: luscii_patient_actions_sdk_ios
description: iOS implementation of the luscii_patient_actions_sdk plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: luscii_patient_actions_sdk
    platforms:
      ios:
        pluginClass: LusciiPatientActionsSdkPlugin
        dartPluginClass: LusciiPatientActionsSdkIOS

dependencies:
  flutter:
    sdk: flutter
  luscii_patient_actions_sdk_platform_interface:
    path: ../luscii_patient_actions_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^9.0.0
