name: luscii_patient_actions_sdk_ios
description: iOS implementation of the luscii_patient_actions_sdk plugin
version: 0.2.0+1
homepage: https://digizorg.app
publish_to: https://dart.cloudsmith.io/digizorg/default/

environment:
  sdk: ^3.8.1

flutter:
  plugin:
    implements: luscii_patient_actions_sdk
    platforms:
      ios:
        pluginClass: LusciiPatientActionsSdkPlugin
        dartPluginClass: LusciiPatientActionsSdkIOS

dependencies:
  flutter:
    sdk: flutter
  luscii_patient_actions_sdk_platform_interface:
    hosted: https://dart.cloudsmith.io/digizorg/default/
    version: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^9.0.0
