name: luscii_patient_actions_sdk_platform_interface

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/luscii_patient_actions_sdk_platform_interface.yaml"
      - "luscii_patient_actions_sdk_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/luscii_patient_actions_sdk_platform_interface.yaml"
      - "luscii_patient_actions_sdk_platform_interface/**"

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      flutter_channel: stable
      flutter_version: 3.32.6
      min_coverage: 15
      working_directory: luscii_patient_actions_sdk_platform_interface
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
